on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-lts
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: xvfb-run -a npm test
  publish:
    name: Release and publish
    needs: test
    runs-on: ubuntu-lts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to VS Code Marketplace
        run: npx vsce publish -p ${{ secrets.VSCODE_TOKEN }}


